[phases.setup]
nixPkgs = ["python311", "freefont_ttf", "dejavu_fonts", "fontconfig"]

[phases.install]
cmds = ["python3 -m ensurepip --upgrade", "python3 -m pip install --upgrade pip", "python3 -m pip install -r requirements.txt"]

[start]
cmd = "python3 main.py"
